In [1]:
import numpy as np

creating a numpy array

In [2]:
x = [1,2,3,4,5]
nx = np.array(x)

In [3]:
nx.ndim

1

In [4]:
y = [[1,2,3],[4,5,6]]
ny = np.array(y)

In [5]:
ny.ndim

2

In [12]:
print(ny)
ny.ndim

[[1 2 3]
 [4 5 6]]


2

In [16]:
nz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nz)
nz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [17]:
nx.shape

(5,)

In [18]:
ny.shape

(2, 3)

In [19]:
nz.shape

(3, 3)

data
----------sequence------------ 
--start end gap
np.arange()
x = np.arange(-10,10,0.5)
--start end size
np.linspace()
y= np.linspace(0,10,5)
-------- random----------
-- float
np.random.rand(5)

In [25]:
x =np.arange(-10,10,0.5)
print(x)
x.ndim


[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5]


1

In [26]:
y = np.linspace(0,10,5)
print(y)

[ 0.   2.5  5.   7.5 10. ]


In [29]:
y = np.linspace(1,50,50)
print(y)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [30]:
a = np.random.rand(10)
print(a)

[0.30803493 0.81056818 0.58267292 0.40670251 0.54392257 0.15918542
 0.61341106 0.61493862 0.44067952 0.92461581]


In [31]:
b = np.random.rand(3,3)
print(b)

[[0.93125011 0.41398771 0.00297204]
 [0.31870541 0.84891082 0.80869366]
 [0.26327075 0.76354565 0.78383035]]


In [33]:
c = np.random.rand(3,3,3)
print(c)

[[[0.73183549 0.49766701 0.40472614]
  [0.26867155 0.51121336 0.67002234]
  [0.39035243 0.03466656 0.48008749]]

 [[0.39007527 0.2223622  0.54339496]
  [0.17321578 0.40424337 0.43611261]
  [0.88414566 0.40679926 0.66655109]]

 [[0.68546719 0.74160928 0.76011192]
  [0.93595533 0.9287975  0.13933755]
  [0.49237023 0.96098513 0.38582817]]]


In [34]:
d = np.random.randint(0,100,(4,4))
print(d)

[[90 46 52 18]
 [19 77 83 40]
 [48 62 35 18]
 [31 62 27 49]]


In [37]:
e = np.random.choice(['😘','😉','😁','💕','💋'],(4,4))
print(e)

[['😉' '😉' '😘' '💕']
 ['💋' '😘' '💕' '😘']
 ['😉' '😘' '😁' '😘']
 ['😘' '😘' '💕' '😉']]


In [41]:
q=np.ones((4,4), dtype=int)
print(q)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [42]:
np.diag(nx)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [45]:
nx.transpose()



array([1, 2, 3, 4, 5])

In [46]:
c.transpose()

array([[[0.73183549, 0.39007527, 0.68546719],
        [0.26867155, 0.17321578, 0.93595533],
        [0.39035243, 0.88414566, 0.49237023]],

       [[0.49766701, 0.2223622 , 0.74160928],
        [0.51121336, 0.40424337, 0.9287975 ],
        [0.03466656, 0.40679926, 0.96098513]],

       [[0.40472614, 0.54339496, 0.76011192],
        [0.67002234, 0.43611261, 0.13933755],
        [0.48008749, 0.66655109, 0.38582817]]])

In [50]:
nz.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
nz.size#number of element

9

In [52]:
nx.dtype

dtype('int32')

In [54]:
x = np.array([[6,9],[6,9]])
y = np.array([[3,2],[1,3]])
print(x+y)

[[ 9 11]
 [ 7 12]]


In [55]:
x+5

array([[11, 14],
       [11, 14]])

In [56]:
x*y

array([[18, 18],
       [ 6, 27]])

In [58]:
x.dot(y)#normal multiplication

array([[27, 39],
       [27, 39]])

In [59]:
np.cross(x,y)

array([-15,   9])

In [60]:
x

array([[6, 9],
       [6, 9]])

In [61]:
np.sin(x)

array([[-0.2794155 ,  0.41211849],
       [-0.2794155 ,  0.41211849]])

In [65]:
y.argmin()

2

In [63]:
y

array([[3, 2],
       [1, 3]])

In [66]:
r = np.random.randint(-101,101,(5,5))
r

array([[-94,  -3,  72,  79,  72],
       [-32,  18,  67, -68, -90],
       [ 24,  97,  -8,  64,  78],
       [-32, -33,  89, -85, -28],
       [-26,  17, 100,  27, -29]])

In [68]:
r.max() , r.min()


(100, -94)

In [69]:
print(r.sum(),r.mean(),r.std(),r.var(),r.prod())

276 11.04 60.58876463503774 3670.9984000000004 0


In [72]:
p = np.random.randint(1,100,(4,4))
print(p)

[[31  6 69 15]
 [ 8 91 10 34]
 [57  2 73  1]
 [33 90 48 28]]


In [74]:
p.max() , p.min()

(91, 1)

In [76]:
p.mean() , p.std()

(37.25, 29.83601012199855)

In [79]:
ab = np.array([[10,2],[34,4]])
print(ab)

[[10  2]
 [34  4]]


In [82]:
ad = np.random.randint(-1,100,(4,4))
print(ad)

[[34 75 26 75]
 [79 88 39 82]
 [86 38 89  1]
 [78 38 29 36]]


In [88]:
v =np.random.choice(['👌','👍','🙌','🤞','✌'] , (5,5))
print(v)

[['🤞' '👌' '🙌' '✌' '✌']
 ['👌' '👌' '👌' '🤞' '🤞']
 ['✌' '👌' '🤞' '✌' '🙌']
 ['🤞' '✌' '👍' '👌' '✌']
 ['✌' '🙌' '👌' '🙌' '🙌']]


In [2]:
import numpy as np
np.random.randint(4,666,(4,4))

array([[114, 645, 554, 407],
       [651, 193, 354, 383],
       [449, 292, 631, 386],
       [473, 549, 125, 393]])

In [3]:
x = np.random.randint(0,101,(3,3))
y = np.random.randint(0,101,(3,3))
print(x,y , sep='\n\n')

[[20 36 40]
 [ 0 19 16]
 [78 37  1]]

[[53 74 52]
 [37 89 64]
 [91  9 43]]


In [4]:
x * y #hadamard product

array([[1060, 2664, 2080],
       [   0, 1691, 1024],
       [7098,  333,   43]])

In [5]:
#maxtrix product dot product
x @ y

array([[6032, 5044, 5064],
       [2159, 1835, 1904],
       [5594, 9074, 6467]])

In [ ]:
# numpy slicing in 2d
arr = [row start : row end : col.start : col end]

In [8]:
# 10 * 5 matrix
a = np.random.randint(10,100,(10,5))
a

array([[13, 92, 20, 22, 76],
       [26, 82, 46, 13, 71],
       [51, 24, 49, 16, 68],
       [28, 38, 80, 47, 93],
       [61, 81, 98, 65, 59],
       [97, 74, 40, 49, 59],
       [22, 15, 21, 74, 52],
       [27, 44, 62, 56, 18],
       [44, 95, 34, 43, 52],
       [85, 45, 24, 33, 67]])

In [10]:
# top 5 rows 
print(a[ :5])

#last 3 row
print(a[-3:])

[[13 92 20 22 76]
 [26 82 46 13 71]
 [51 24 49 16 68]
 [28 38 80 47 93]
 [61 81 98 65 59]]
[[27 44 62 56 18]
 [44 95 34 43 52]
 [85 45 24 33 67]]


In [12]:
#1 column
print(a[:,1])

#first 3 column
print(a[:,:3])

[92 82 24 38 81 74 15 44 95 45]
[[13 92 20]
 [26 82 46]
 [51 24 49]
 [28 38 80]
 [61 81 98]
 [97 74 40]
 [22 15 21]
 [27 44 62]
 [44 95 34]
 [85 45 24]]
